apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: parking-service
  name: parking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: parking-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: parking-service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres-service;Port=5432;Database=SmartParkDatabase;Username=postgres;Password=turisticka
          image: smartparks1acr.azurecr.io/rso-project2024-copy-parking-service:latest
          name: parking-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
