apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres-service
  name: postgres-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: postgres-service
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: SmartParkDatabase
            - name: POSTGRES_PASSWORD
              value: turisticka
            - name: POSTGRES_USER
              value: postgres
          image: postgres:latest
          name: postgres-service
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
