apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: LoadBalancer  # LoadBalancer from values.yaml
  ports:
    - name: "80"
      port: {{ .Values.frontend.service.port }}  # Use port from values.yaml
      targetPort: {{ .Values.frontend.service.port }}  # Use targetPort from values.yaml
  selector:
    io.kompose.service: frontend
