apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-service1
  labels:
    app: postgres-service1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres-service1
  template:
    metadata:
      labels:
        app: postgres-service1
    spec:
      containers:
        - name: postgres1
          image: "{{ .Values.postgresService.image.repository }}:{{ .Values.postgresService.image.tag }}"
          ports:
            - containerPort: {{ .Values.postgresService.service.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresService.env.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresService.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresService.env.POSTGRES_PASSWORD }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
