apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service1
  labels:
    app: reservation-service1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: reservation-service1
  template:
    metadata:
      labels:
        app: reservation-service1
    spec:
      containers:
        - name: reservation-service1
          image: "{{ .Values.reservationService.image.repository }}:{{ .Values.reservationService.image.tag }}"
          ports:
            - containerPort: {{ .Values.reservationService.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.reservationService.env.ASPNETCORE_ENVIRONMENT }}
            - name: ASPNETCORE_URLS
              value: {{ .Values.reservationService.env.ASPNETCORE_URLS }}
            - name: ConnectionStrings__DefaultConnection
              value: {{ .Values.reservationService.env.ConnectionStrings__DefaultConnection }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
