apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: reservation-service1
  name: reservation-service1
spec:
  ports:
    - name: "8082"
      port: {{ .Values.reservationService.service.port }}  # Use port from values.yaml
      targetPort: {{ .Values.reservationService.service.port }}  # Use targetPort from values.yaml
  selector:
    io.kompose.service: reservation-service1
